version: '3'
services:
  meeting-timeline:
    image: meeting-timeline:latest
    environment:
      - TZ=America/Los_Angeles
      - REDIS_HOST=redis
    ports:
     - "3000:3000"
    links:
     - redis:redis
  redis:
    image: "redis:alpine"
